version: '3'
services:
  mongo:
    image: mongo
    restart: always
    networks: 
      - mongo-compose-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hello
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      # got a mongo local. alias for convenience.
      - 27020:27017

  api:
    build: 
      context: ./vev-test-backend
      dockerfile: Dockerfile
    restart: always
    networks: 
      - mongo-compose-network
    environment:
      - MONGO_URI=mongodb://root:hello@localhost:27020/?authSource=admin&authMechanism=SCRAM-SHA-256
      - MONGO_DB=
    ports:
    # Using port 3K Most of the time. alias for convenience.
      - 3002:3002


networks:
  mongo-compose-network:
    driver: bridge